### ISSUE TITLE
Is CDL really just for UPB? ;-)

### ISSUE THREAD

**Issue by vcarbune** [rosedu/cdl.rosedu.org#10]
[...] pentru studenții din Universitatea Politehnica din București, [...]

**Comment by ghost** [comment]
It makes a lot of sense to change this, mai ales ca Laura a zis ca o sa dea vestea printre oamenii de la alte facultati (mate-info?).
Intrebarea ar fi - cum definesti target audience.
De exemplu, textul de mai sus ar putea fi inlocuit cu "[...] cursul este dedicat tuturor celor pasionati de programare [...]"

**Comment by gvoicu** [comment]
Sau ca sa mergem unpic mai concentrat pe elevi si studenti "[...] cursul este dedicat tuturor elevilor si studentilor pasionati de programare [...]" ?

**Comment by lauuuuuura** [comment]
Cred că merge mult mai bine cum zice Gabi :)
