### ISSUE TITLE
Kreator.js description

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/cdl.rosedu.org#2]
Este singurul proiect ce are descrierea in engleza si cred ca ar trebui tradusa.

**Comment by piatra** [comment]
Eu nu as vrea asta. In alta ordine de idei voi continua aici cu issue-urile mele
1. kreator.js (no uppercase)
2. @ resources pe pagina proiectului meu linkul "http://w3fools.com" a fost scos din context, eu am spus sa nu foloseasca w3schools ca sursa de documentatie si am adaugat acel link ca motivatie.
3. adauga te rog si twitter handler-ul dupa numele meu @ an_rei

**Comment by tiriplicamihai** [comment]
Dacă vrei ca descrierea să fie în engleză va rămâne așa.
