### ISSUE TITLE
Menu doesn't show when screen is small

### ISSUE THREAD

**Issue by tudalex** [rosedu/cdl.rosedu.org#4]
When you have a very small window the menu disappears instead of just being above the title.

**Comment by ghost** [comment]
This behavior is by design.

The intention behind the responsive design was to unclutter the interface as much as possible when displayed on a mobile device. Access to the diferent sections still exists, but is done via the additional grey buttons which appear on the home page when you have a very narrow viewport.

I would be very interested to know if this design decision is potentially confusing.

**Comment by tudalex** [comment]
From my point it's confusing on the other pages( not the main page) cause there is no back button and you have to press your browser's back button. Also the buttons don't look like menu buttons and their placement has nothing to do with navigation (users tend to find navigation buttons on the top side of the page, ex: twitter, facebook, microsoft...) Also navigation buttons seem to have full width of the device or at least constant width.
For me it seems unnatural. Maybe I am wrong. Feel free to close this issue if it's a design decision you are not willing to change.

**Comment by ghost** [comment]
I am going to leave the issue open.

This is my first attempt at designing a mobile user experience and I'm still figuring out how to adapt that experience to mobile users' expectations without breaking the desktop side of the user experience.

You have raised some valid points and I don't have a good answer to most of them at this time. I am going to discuss these considerations with a few friends who have a very good understanding of mobile design, and see what they come up with.

Having said that ...

> "there is no back button and you have to press your browser's back button"

... this statement is slightly puzzling. I thought a person would fully realize that they are viewing this content through the browser, not through a native app, and therefore would not expect the site to include a back button of its own, within its HTML markup.

**Comment by ghost** [comment]
I made the navigation buttons on the main page full-width on narrow form factors.
Addressing the other findings in this bug report will affect the desktop layout as well, so they are going to require careful consideration.
Keeping this issue open.
