### ISSUE TITLE
Așezare text în pagină

### ISSUE THREAD

**Issue by tiriplicamihai** [rosedu/cdl.rosedu.org#6]
Este o problemă cu așezarea în pagină a textului. Partea gri închis din subsolul paginii se suprapune cu ultimele rânduri.

**Comment by ghost** [comment]
Salut, ataseaza, te rog, un screenshot. In ce versiune de browser se intampla?

**Comment by tiriplicamihai** [comment]
Încă este problema. Am atașat un screenshot[1]. Ideea este că acum este cam greu de resetat pentru că s-au făcut mai multe commit-uri și se pierde informație. Pe moment cred că o să îl lăsăm așa.

[1] http://swarm.cs.pub.ro/~mtiriplica/CDLbug.png

**Comment by ghost** [comment]
Am ascuns footer-ul momentan.
Testeaza asa, ar trebui sa nu se mai vada urat.
Cred ca in cele din urma o sa mutam informatia importanta din footer in pagina "organizatori".

**Comment by tiriplicamihai** [comment]
Se vede ok acum. Mulțumim!
